# Generated by Django 4.1.1 on 2022-11-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_saved_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_icon_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='summoner_level',
            field=models.IntegerField(null=True),
        ),
    ]
