# Generated by Django 4.1.1 on 2022-11-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_profile_icon_id_player_summoner_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='summoner_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
