# Generated by Django 4.1.1 on 2022-11-17 11:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('players', '0013_alter_player_summoner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlayers',
            fields=[
                ('saved_players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='saved_players',
        ),
    ]
