# Generated by Django 4.1.1 on 2022-10-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_otherplayers_rename_nick_player_summoner_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otherplayers',
        ),
    ]
