# Generated by Django 4.1.1 on 2022-11-03 11:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_summoner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='saved_players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None, unique=True),
        ),
    ]
