# Generated by Django 4.1.1 on 2022-11-03 11:44

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_player_saved_players'),
    ]

    operations = [
        CITextExtension(),
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='saved_players',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CITextField(max_length=100), default=list, size=None, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='summoner_name',
            field=django.contrib.postgres.fields.citext.CITextField(primary_key=True, serialize=False),
        ),
    ]
